CREATE SCHEMA IF NOT EXISTS raw;

DROP TABLE IF EXISTS raw.listings;
CREATE TABLE raw.listings (
  id TEXT,
  listing_url TEXT,
  scrape_id TEXT,
  last_scraped TEXT,
  source TEXT,
  name TEXT,
  description TEXT,
  neighborhood_overview TEXT,
  picture_url TEXT,
  host_id TEXT,
  host_url TEXT,
  host_name TEXT,
  host_since TEXT,
  host_location TEXT,
  host_about TEXT,
  host_response_time TEXT,
  host_response_rate TEXT,
  host_acceptance_rate TEXT,
  host_is_superhost TEXT,
  host_thumbnail_url TEXT,
  host_picture_url TEXT,
  host_neighbourhood TEXT,
  host_listings_count TEXT,
  host_total_listings_count TEXT,
  host_verifications TEXT,
  host_has_profile_pic TEXT,
  host_identity_verified TEXT,
  neighbourhood TEXT,
  neighbourhood_cleansed TEXT,
  neighbourhood_group_cleansed TEXT,
  latitude TEXT,
  longitude TEXT,
  property_type TEXT,
  room_type TEXT,
  accommodates TEXT,
  bathrooms TEXT,
  bathrooms_text TEXT,
  bedrooms TEXT,
  beds TEXT,
  amenities TEXT,
  price TEXT,
  minimum_nights TEXT,
  maximum_nights TEXT,
  minimum_minimum_nights TEXT,
  maximum_minimum_nights TEXT,
  minimum_maximum_nights TEXT,
  maximum_maximum_nights TEXT,
  minimum_nights_avg_ntm TEXT,
  maximum_nights_avg_ntm TEXT,
  calendar_updated TEXT,
  has_availability TEXT,
  availability_30 TEXT,
  availability_60 TEXT,
  availability_90 TEXT,
  availability_365 TEXT,
  calendar_last_scraped TEXT,
  number_of_reviews TEXT,
  number_of_reviews_ltm TEXT,
  number_of_reviews_l30d TEXT,
  availability_eoy TEXT,
  number_of_reviews_ly TEXT,
  estimated_occupancy_l365d TEXT,
  estimated_revenue_l365d TEXT,
  first_review TEXT,
  last_review TEXT,
  review_scores_rating TEXT,
  review_scores_accuracy TEXT,
  review_scores_cleanliness TEXT,
  review_scores_checkin TEXT,
  review_scores_communication TEXT,
  review_scores_location TEXT,
  review_scores_value TEXT,
  license TEXT,
  instant_bookable TEXT,
  calculated_host_listings_count TEXT,
  calculated_host_listings_count_entire_homes TEXT,
  calculated_host_listings_count_private_rooms TEXT,
  calculated_host_listings_count_shared_rooms TEXT,
  reviews_per_month TEXT
);

DROP TABLE IF EXISTS raw.reviews;
CREATE TABLE raw.reviews (
  listing_id TEXT,
  id TEXT,
  date TEXT,
  reviewer_id TEXT,
  reviewer_name TEXT,
  comments TEXT
);
